### ISSUE TITLE
cherrytree-future-0.99.33.20210330git68a5ef3-1 crashes

### ISSUE THREAD

**Issue by mepreston** [funnelfiasco/copr-cherrytree#16] opened 2021-04-17 13:34 UTC
Hi,
after upgrading via dnf cherrytree-future crashes when i start it.
Segmentation fault (core dumped)

It works fine when i downgrade to previous version.

what info do you need?

crashes: cherrytree-future-0.99.33.20210413gitc8f974e-1.fc33.x86_64
works: cherrytree-future-0.99.33.20210330git68a5ef3-1.fc33.x86_64

cheers,
m.

**Comment by funnelfiasco** [comment] 2021-04-17 13:42
Hm. It's probably an upstream issue. I'll see if I can reproduce it and if I can, I'll find the commit that breaks it.

**Comment by funnelfiasco** [comment] 2021-04-17 20:36
Unfortunately, I can't reproduce this on F33 Workstation. Could you try removing the file `~/.config/cherrytree/config.cfg.tmp` if it exists and removing any line that starts with `doc_` in `~/.config/cherrytree/config.cfg`? This will make CherryTree launch with a new file.

Do you get any output when running `cherrytree` from the command line or does it dump core immediately?

**Comment by mepreston** [comment] 2021-04-18 12:33
hi,  i removed the doc_  lines and still have the same issue.  Here is what happens when i start it from the command line:
$ cherrytree
** Message: 08:27:16.349: Language overwrite = en (localedir = /usr/share/locale)

(process:601071): Gtk-WARNING **: 08:27:16.366: Locale not supported by C library.
Using the fallback 'C' locale.
[2021-04-18 08:27:16.505] [   ] [debug] /home/mark.preston/.config/cherrytree/config.cfg parsed
[2021-04-18 08:27:16.707] [   ] [debug] autosave is started
Segmentation fault (core dumped)

**Comment by funnelfiasco** [comment] 2021-04-18 20:13
Looks, like there's an [upstream commit](https://github.com/giuspen/cherrytree/commit/5c5b6cb644bfbce32a99dad8633a59e744ca1333) that may address this. There are other reports of segfaults that appear to be fixed in the latest release. I'll kick off an update shortly for you to try.

**Comment by funnelfiasco** [comment] 2021-04-18 21:18
@mepreston the x86_64 build for Fedora 33 has completed. You can `dnf --refresh update cherrytree-future` or [download the RPM directly](https://download.copr.fedorainfracloud.org/results/bcotton/cherrytree/fedora-33-x86_64/02139319-cherrytree-future/cherrytree-future-0.99.36.20210418gitcee0d39-1.fc33.x86_64.rpm) and give it a try.

**Comment by mepreston** [comment] 2021-04-18 21:22
Hi,  I've tested and that has resolved the crashing issue.  All seems to be working well now.  Thanks for the very fast response.

**Comment by funnelfiasco** [comment] 2021-04-18 21:53
Great to hear it!

**Closed by funnelfiasco** 2021-04-18 21:53 UTC
Labels: Cherrytree future, bug
